id: I459BF3F9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T15:08:06+00:00'
last_modified: '2022-06-09T06:29:26.105795+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24101
  title: བདེན་པ་གཉིས་ལ་འཇུག་པ་ལ་སོགས་པའི་གཞུང་ཚན་བཞི།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '4994':
      image_group_id: I1KG24234
      title: Volume 1 of bden pa gnyis la 'jug pa la sogs pa'i gzhung tshan bzhi/
      total_pages: 188
      order: 1
      base_file: 4994.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
