id: P007843
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24101
  title: བདེན་པ་གཉིས་ལ་འཇུག་པ་ལ་སོགས་པའི་གཞུང་ཚན་བཞི།
  author: ''
  volumes:
    b5e1487019b64a0998a1592c4b9bf549:
      image_group_id: I1KG24234
      title: ''
      volume_number: 1
      total_pages: 188
ebook_metadata:
  title: བདེན་པ་གཉིས་ལ་འཇུག་པ་ལ་སོགས་པའི་གཞུང་ཚན་བཞི།
  author: ''
  sku: P007843
  cover: cover.jpg
  layers:
  - pagination
